### ISSUE TITLE
configure: error: --with-openssl-rpath "/usr/local/ssl/lib" is not a directory; ModuleNotFoundError: No module named '_sha2'/'_hashlib'

### ISSUE THREAD

**Issue by shashankram** [egibs/python-fips#1]
Hi, I tried building python-3.12 with both rocky and wolfi and see the following error:
```
22.38 checking for shm_open... yes
22.44 checking for shm_unlink... yes
22.49 checking for include/openssl/ssl.h in /usr/local/ssl... yes
22.49 checking whether compiling and linking against OpenSSL works... no
22.57 checking for --with-openssl-rpath... configure: error: --with-openssl-rpath "/usr/local/ssl/lib" is not a directory
------
```

This is from the `--with-openssl-rpath=/usr/local/ssl/lib` argument. Not sure if this path is incorrect, but setting this to `auto` allows the build to proceed further. However, it fails with a different error:
```
334.0 (cd /opt/python-fips/share/man/man1; ln -s python3.12.1 python3.1)
334.0 if test "xupgrade" != "xno"  ; then \
334.0 	case upgrade in \
334.0 		upgrade) ensurepip="--upgrade" ;; \
334.0 		install|*) ensurepip="" ;; \
334.0 	esac; \
334.0 	LD_LIBRARY_PATH=/fips/Python-3.12.3:/usr/local/lib/:/usr/local/lib64/ ./python -E -m ensurepip \
334.0 		$ensurepip --root=/ ; \
334.0 fi
334.0 Traceback (most recent call last):
334.0   File "/fips/Python-3.12.3/Lib/random.py", line 68, in <module>
334.0     from _sha2 import sha512 as _sha512
334.0 ModuleNotFoundError: No module named '_sha2'
334.0 
334.0 During handling of the above exception, another exception occurred:
334.0 
334.0 Traceback (most recent call last):
334.0   File "<frozen runpy>", line 189, in _run_module_as_main
334.0   File "<frozen runpy>", line 148, in _get_module_details
334.0   File "<frozen runpy>", line 112, in _get_module_details
334.0   File "/fips/Python-3.12.3/Lib/ensurepip/__init__.py", line 7, in <module>
334.0     import tempfile
334.0   File "/fips/Python-3.12.3/Lib/tempfile.py", line 45, in <module>
334.0     from random import Random as _Random
334.0   File "/fips/Python-3.12.3/Lib/random.py", line 71, in <module>
334.0     from hashlib import sha512 as _sha512
334.0   File "/fips/Python-3.12.3/Lib/hashlib.py", line 78, in <module>
334.0     import _hashlib
334.0 ModuleNotFoundError: No module named '_hashlib'
334.0 make: *** [Makefile:2030: install] Error 1
------
```

**Comment by egibs** [comment]
Hey, thanks for reaching out! I'll look into this and push a fix.

**Comment by shashankram** [comment]
`mkdir -p /usr/local/ssl/lib` resolved the first problem, and the second one seems to be due to:
```
#18 243.7 The necessary bits to build these optional modules were not found:
#18 243.7 _curses               _curses_panel         _dbm               
#18 243.7 _gdbm                 _hashlib              _ssl               
#18 243.7 _tkinter              _uuid                 nis                
#18 243.7 readline                                                       
#18 243.7 To find the necessary bits, look in configure.ac and config.log.
#18 243.7 
#18 243.7 Could not build the ssl module!
#18 243.7 Python requires a OpenSSL 1.1.1 or newer
```
I was trying to compile Python 3.12 with openssl-1.0.9, which isn't going to work.

**Comment by egibs** [comment]
Ah, good catch! Yea, `1.0.2u` for `3.9` and then OpenSSL `3.0.9` for `3.11` and `3.12` were the magic combination in my testing.

**Comment by shashankram** [comment]
@egibs do you know why the Python patch is required? What's the purpose of applying that patch?

**Comment by egibs** [comment]
> @egibs do you know why the Python patch is required? What's the purpose of applying that patch?

They're mostly required to handle the configuration of algorithms that are or are not allowed when using FIPS.

With the Python3.11 and 3.12 patches, support for the FIPS-enabled OpenSSL implementations of the algorithms is added rather than relying on the Python built-ins (in the case of `blake2s` and `blake2b`) or removed entirely in the case of MD5.

The Python 3.9 patch adds the `FIPS_mode` and `FIPS_mode_set` methods which tells Python which algorithms can/cannot be used.

**Comment by shashankram** [comment]
Thanks @egibs. Where do you see md5 disabled in the patch? Because I only see test code pertaining to md5. 

I also noticed the [3.12 patch](https://gitlab.com/redhat/centos-stream/rpms/python3.12/-/blob/c8s/00329-fips.patch?ref_type=heads) was updated recently, so you may want to update your repo.

**Comment by egibs** [comment]
> Where do you see md5 disabled in the patch? Because I only see test code pertaining to md5.

It's the code like the following two instances which aren't necessarily MD5-specific (the other part of this is building Python without MD5/Blake2 support):
- https://github.com/egibs/python-fips/blob/97acbd26c065f43406c4c054678f6d566855178a/fips_3.11.patch#L231-L234
- https://github.com/egibs/python-fips/blob/97acbd26c065f43406c4c054678f6d566855178a/fips_3.11.patch#L486-L487

Building Python without `md5`:
```
--with-builtin-hashlib-hashes=sha1,sha256,sha512,sha3
```

Trying to use `md5` within Python:
```py
>>> hashlib.new('md5')
...
...
ValueError: unsupported hash type md5(in FIPS mode)
```

If that doesn't answer your question let me know!

> I also noticed the [3.12 patch](https://gitlab.com/redhat/centos-stream/rpms/python3.12/-/blob/c8s/00329-fips.patch?ref_type=heads) was updated recently, so you may want to update your repo.

Thanks! I updated both the 3.11 and 3.12 patches with the latest upstream versions.

**Comment by shashankram** [comment]
That makes sense, though I am confused why the [usedforsecurity](https://docs.python.org/3/library/hashlib.html#constructors) flag is unusable with the patches:
```
>>> hashlib.md5(usedforsecurity=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'hashlib' has no attribute 'md5'
```

Per my understanding, the `usedforsecurity=False` flag enables using md5 and other insecure hashes for non-crypto use cases. It seems with this patch, these are unusable?
